server:
  port: 8083

spring:
  application:
    name: product-application

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    service-url:
#      default-zone: https://localhost:8761/eureka
#    instance:
#      hostname: localhost