server:
  port: 8085

spring:
  application:
    name: gateway-application
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enable: true
#          lowerCaseServiceId: true
#        routes:
#         - id: product-route
#           uri: http://localhost:8083/
#           predicates:
#             - Path=/product/getByUniqueId/**
#             - Path=/product/getBySku/**
#           filters:
#             - RewritePath=/product/(?<path>.*), /$\{path}




eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
    instance:
      hostname: localhost
      prefer-ip-address: true