server:
  port: 8083

spring:
  application:
    name: product-application

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
    instance:
      hostname: localhost
      prefer-ip-address: true

resilience4j.circuitbreaker:
  instances:
    productCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 1
      slidingWindowType: TIME_BASED
      waitDurationInOpenState: 5s
      eventConsumerBufferSize: 10
      minimumNumberOfCalls: 4
      failureRateThreshold: 50