
server:
  port: 8888

spring:
  application:
    name: config-application

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  security:
    user:
      password: password

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
    instance:
      hostname: localhost
      prefer-ip-address: true
