
server:
  port: 8888

spring:
  application:
    config-server

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  security:
    user:
      password: password
